---
#- name: download and install elastic GPG key
#  ansible.builtin.rpm_key:
#    state=present
#    key=https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Create repo for Elastic packages
  ansible.builtin.yum_repository:
    name: elasticsearch
    description: Elastic 7.x Repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Import Elasticsearch GPG key
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    hash_algorithm: sha512


- name: Enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
  notify: firewall

- name: Flush handlers
  meta: flush_handlers
...
